# Generated by Django 3.1.4 on 2020-12-14 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
